-- Create table configuration --
create table dbo.configuration
(
    id INT IDENTITY(1,1) NOT NULL,
    kafka_topic            VARCHAR(250) NULL,
    kafka_topic_accumulate VARCHAR(250) NULL,
    job_name               VARCHAR(250) NULL,
    accumulate_job_key     VARCHAR(250) NULL,
    CONSTRAINT PK_CONFIGURATION PRIMARY KEY (id)
);

-- Data for configuration table --
insert into dbo.configuration (kafka_topic, kafka_topic_accumulate, job_name, accumulate_job_key)
values  (N'kafka-topic-prefix.TOPOVN.AGENT', N'ecm_agent', N'com.kd.snp.datahub.flink.AgentJobPipeline', N'AGENT'),
        (N'TOPOVN_TCCL_G1.TOPOVN.ITEM_REEFER', N'ecm_reefer_container', N'com.kd.snp.datahub.flink.ItemReeferJobPipeline', N'ITEM_KEY'),
        (N'kafka-prefix.TOPOVN.ITEM_PTI', N'ecm_reefer_container', N'com.kd.snp.datahub.flink.ItemPtiJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM', N'ecm_container,ecm_reefer_container,ecm_quay_job,ecm_yard_job', N'com.kd.snp.datahub.flink.ItemJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G2.TOPOVN.PREGATE_TRANSACT', N'ecm_container,ecm_reefer_container,ecm_gate_job,ecm_quay_job', N'com.kd.snp.datahub.flink.PregateTransactJobPipeline', N'ITEM_KEY,EIR_ID'),
        (N'TOPOVN_TCCL_G1.TOPOVN.SYS_CODES', N'ecm_job,ecm_class,ecm_container_type,ecm_method,ecm_container_condition,ecm_vendor', N'com.kd.snp.datahub.flink.SysCodesJobPipeline', N'CODE_REF'),
        (N'TOPOVN_TCCL_G1.CHARGE_CODES', null, N'com.kd.snp.datahub.flink.ChargeCodesJobPipeline', N'CHARGE_CD'),
        (N'TOPOVN_TCCL_G1.TOPOVN.OPERATION_METHOD', N'ecm_job_mode', N'com.kd.snp.datahub.flink.OperationMethodJobPipeline', N'OPERATION_METHOD'),
        (N'TOPOVN_TCCL_G2.TOPOVN.VESSEL_DETAILS', N'ecm_vessel_schedule', N'com.kd.snp.datahub.flink.VesselDetailsJobPipeline', N'VES_ID'),
        (N'TOPOVN.ITEM_COMMENTS', N'ecm_container', N'com.kd.snp.datahub.flink.ItemCommentsJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN.ITEM_SEAL', N'ecm_container', N'com.kd.snp.datahub.flink.ItemSealJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G1.TOPOVN.ITEM_SPECIAL_HANDLING', N'ecm_container', N'com.kd.snp.datahub.flink.ItemSpecialHandlingJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G2.TOPOVN.ITEM_STOPS', N'ecm_container', N'com.kd.snp.datahub.flink.ItemStopsJobPipeline', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM_LOCATION', N'ecm_container,ecm_quay_job,ecm_yard_job', N'com.kd.snp.datahub.flink.ItemLocationJobPipeline', N'ITEM_KEY'),
        (N'kafka-topic-prefix.TOPOVN.LINE_OPER', N'ecm_operation', N'com.kd.snp.datahub.flink.LineOperJobPipeline', N'LINE_OPER'),
        (N'TOPOVN_TCCL_G1.TOPOVN.YARD_AREA', N'ecm_container,ecm_yard', N'com.kd.snp.datahub.flink.YardAreaJobPipeline', N'STACK'),
        (N'config_stopcode', N'ecm_container', N'com.kd.snp.datahub.flink.ConfigStopCodeJobPipeline', N'STOP_CODE'),
        (N'TOPOVN_TCCL_G1.TOPOVN.CUSTOMER', N'ecm_customer', N'com.kd.snp.datahub.flink.CustomerJobPipeline', N'CUST_REG_NO'),
        (N'TOPOVN_TCCL_G1.TOPOVN.VES_SERVICE', N'ecm_vessel_lane', N'com.kd.snp.datahub.flink.VesServiceJobPipeline', N'VES_SERVICE'),
        (N'kafka-topic-prefix.TOPOVN.GATE_LANE_INFO', N'ecm_gate', N'com.kd.snp.datahub.flink.GateLaneInfoJobPipeline', N'GATE_NO'),
        (N'kafka-topic-prefix.TOPOVN.GATE_NO_INFO', N'ecm_gate', N'com.kd.snp.datahub.flink.GateLaneNoJobPipeline', N'GATE_NO'),
        (N'kafka-topic-prefix.TOPOVN.PORTCODE', N'ecm_port', N'com.kd.snp.datahub.flink.PortCodeJobPipeline', N'PORT'),
        (N'TOPOVN_TCCL_G1.TOPOVN.VESSELS', N'ecm_vessel', N'com.kd.snp.datahub.flink.VesselsJobPipeline', N'VES_CD'),
        (N'kafka-topic-prefix.TOPOVN.DAMAGE_CODE', N'ecm_damage_code', N'com.kd.snp.datahub.flink.DamageCodeJobPipeline', N'DAMAGE_CD'),
        (N'kafka-topic-prefix.TOPOVN.SEAL_MANAGEMENT_MASTER', N'ecm_seal_management', N'com.kd.snp.datahub.flink.SealManagementMasterJobPipeline', N'SEALFORMAT'),
        (N'kafka-topic-prefix.TOPOVN.SPECIAL_HDL_CODE', N'ecm_special_handling', N'com.kd.snp.datahub.flink.SpecialHdlCodeJobPipeline', N'SPECIAL_HDL_CODE'),
        (N'kafka-topic-prefix.TOPOVN.CONTAINER_STRUCTURE', N'ecm_container_spec', N'com.kd.snp.datahub.flink.ContainerStructureJobPipeline', N'ITEM_NO'),
        (N'kafka-topic-prefix.TOPOVN.CHE_MASTER', N'ecm_equipment', N'com.kd.snp.datahub.flink.CheMasterJobPipeline', N'CHE_ID'),
        (N'kafka-topic-prefix.TOPOVN.RA_COMMON', N'ecm_booking', N'com.kd.snp.datahub.flink.RaCommonJobPipeline', N'RAC_KEY'),
        (N'kafka-topic-prefix.TOPOVN.RA_MTY', N'ecm_booking', N'com.kd.snp.datahub.flink.RaMtyJobPipeline', N'RAC_KEY'),
        (N'TOPOVN_TCCL_G2.TOPOVN.RA_SPECIFIC_CTRS', N'ecm_booking', N'com.kd.snp.datahub.flink.RaSpecificCtrsJobPipeline', N'RAC_KEY'),
        (N'kafka-topic-prefix.TOPOVN.TRUCK', null, N'com.kd.snp.datahub.flink.TruckJobPipeline', N'TRK_KEY'),
        (N'kafka-topic-prefix.TOPOVN.TRK_TRANSACT', N'ecm_gate_job', N'com.kd.snp.datahub.flink.TrkTransactJobPipeline', N'EIR_ID'),
        (N'kafka-topic-prefix.TOPOVN.CTNR_MOVE_REG_MASTER', N'ecm_service_order', N'com.kd.snp.datahub.flink.CtnrMoveRegMasterJobPipeline', N'REG_ID'),
        (N'kafka-topic-prefix.TOPOVN.CTNR_MOVE_REG_DETAILS', N'ecm_yard_job,ecm_service_order', N'com.kd.snp.datahub.flink.CtnrMoveRegDetailsJobPipeline', N'ITEM_KEY,REG_ID'),
        (N'kafka-topic-prefix.TOPOVN.CONVERT_ISO', N'ecm_size_type', N'com.kd.snp.datahub.flink.ConvertIsoJobPipeline', N'ORIGINAL_ISO'),
        (N'TOPOVN_TCCL_G1.TOPOVN.CONVERT_TO_ISO', N'ecm_size_type', N'com.kd.snp.datahub.flink.ConvertToIsoJobPipeline', N'ISO'),
        (N'TOPOVN_TCCL_G2.TOPOVN.PREGATE_REEFER', N'ecm_quay_job', N'com.kd.snp.datahub.flink.PreGateReferJobPipeline', null),
        (N'EPORT_NEW.EPORT.dbo.CHARGE', null, N'com.kd.snp.datahub.flink.EportChargeJobPipeline', null),
        (N'EPORT_NEW.EPORT.dbo.INVOICE', null, N'com.kd.snp.datahub.flink.EportInvoiceJobPipeline', null),
        (N'EPORT_NEW.EPORT.dbo.ORDER', null, N'com.kd.snp.datahub.flink.EportOrderJobPipeline', null),
        (N'EPORT_NEW.EPORT.dbo.ORDER_DETAIL', null, N'com.kd.snp.datahub.flink.EportOrderDetailJobPipeline', null),
        (N'TOPOVN_TCCL_G8.TOPOVN.FREE_RULES', null, N'com.kd.snp.datahub.flink.FreeRulesJobPipeline', null),
        (N'TOPOVN_TCCL_G3.TOPOVN.INVOICE', null, N'com.kd.snp.datahub.flink.InvoiceJobPipeline', N'ID'),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM_CHARGES', null, N'com.kd.snp.datahub.flink.ItemChargesJobPipeline', N'ID'),
        (N'TOPOVN_TCCL_G2.TOPOVN.ITEM_STRIP_STUFF', null, N'com.kd.snp.datahub.flink.ItemStripStuffJobPipeline', null);