CREATE TABLE dbo.configuration_accumulate (
	id INT IDENTITY(1,1) NOT NULL,
	kafka_topic VARCHAR(250) NULL,
	accumulate_view_query NVARCHAR(MAX) NULL,
	job_name VARCHAR(250) NULL,
	accumulate_key VARCHAR(250) NULL,
	CONSTRAINT PK_CONFIGURATION_ACCUMULATE PRIMARY KEY (id)
);

INSERT INTO dbo.configuration_accumulate (kafka_topic,accumulate_view_query,job_name,accumulate_key) VALUES
	 (N'ecm_agent',N'SELECT
            "AGENT" AS AGENT,
            "LINE_OPER" AS OPERATION_CODE,
            "AS_AT_TS" AS APPLY_DATE,
            "EXPIRY_TS" AS EXPIRE_DATE,
            CASE WHEN "IS_CONT_AGENT" = ''Y'' THEN 1 ELSE 0 END AS IS_CONTAINER_AGENT,
            "OP"
        FROM SCHEMA_NAME."AGENT"
        WHERE "AGENT" = ?',N'com.kd.snp.datahub.flink.AgentAccumulateJobPipeline',N'AGENT'),
	 (N'ecm_port',N'SELECT
    PORT AS PORT_CODE,
    DESCR AS PORT_NAME,
    OP
FROM TOPOVN_TCCL.PORTCODE
where PORT = ?',N'com.kd.snp.datahub.flink.PortAccumulateJobPipeline',N'PORT_CODE'),
	 (N'ecm_vessel_lane',N'SELECT
	VS1.VES_SERVICE AS LANE_CODE,
	VS1.SERVICE_NAME AS LANE_NAME,
	'''' AS OPERATION_CODE,
	LISTAGG(VS1.DISCH_PORT, '', '') WITHIN GROUP (ORDER BY VS1.VES_SERVICE, VS1.SEQ_NO) AS PORT_CODE,
	CASE WHEN VS2.OP = ''c'' AND COUNT(1) = 1 THEN ''c''
		WHEN VS2.OP = ''d'' AND COUNT(1) = 1 THEN ''d''
		ELSE ''u'' END AS OP
FROM SCHEMA_NAME.VES_SERVICE VS1
	INNER JOIN (SELECT VES_SERVICE, OP
				FROM (
					SELECT
						VES_SERVICE,
						OP,
						ROW_NUMBER() OVER (PARTITION BY VES_SERVICE ORDER BY LAST_MODIFIED_DATE DESC) AS RN
					FROM SCHEMA_NAME.VES_SERVICE
				) SUB
				WHERE RN = 1) VS2 ON VS1.VES_SERVICE = VS2.VES_SERVICE
WHERE VS1.VES_SERVICE = ?
GROUP BY VS1.VES_SERVICE,
	VS1.SERVICE_NAME,
	VS2.OP',N'com.kd.snp.datahub.flink.VesselLaneAccumulateJobPipeline',N'LANE_CODE'),
	 (N'ecm_class',N'SELECT
    CODE_REF AS class_code,
    DESCR AS class_name,
    OP
	FROM SCHEMA_NAME.SYS_CODES WHERE CODE_TP = ''IMPEXP'' and CODE_REF = ?',N'com.kd.snp.datahub.flink.ClassAccumulateJobPipeline',N'CLASS_CODE'),
	 (N'ecm_container',N'WITH ITEM_FILTERED AS (
SELECT 
     I.ITEM_KEY,          
     I.BILL_OF_LADING,
     I.BOOK_NO,
     I.ITEM_NO,
     I.CATEGORY,
     I.LINE_OPER,
     I.AGENT,
     I.FEL,
     I.ITEM_TYPE,
     I.ISO AS LOCAL_SIZE_TYPE,                    
     I.ARR_BY,
     I.CONSIGNOR,
     I.ARR_TS,
     I.DEP_TS,
     I.DEP_BY,
     I.TARE,
     I.LOAD_PORT,
     I.DISCH_PORT,
     I.FDISCH_PORT,
     I.LL_DISCH_PORT,
     I.GRADE,
     I.EIR_ID,
     I.HIST_FLG,
     I.OP AS OP,
     I.DEP_CAR,
     I.ARR_CAR, 
     I.LAST_MODIFIED_DATE
FROM SCHEMA_NAME.ITEM I 
WHERE I.FEL = ''E''
     AND EXTRACT(YEAR FROM I.ARR_TS) != 1900
     --AND (I.ARR_BY = ''P'' OR I.DEP_BY = ''P'')
     --AND I.ARR_TS > NOW() - INTERVAL ''180 DAYS''
     AND I.ITEM_KEY = %s
    --LIMIT 200
),
VESSEL_DETAILS_FILTERED AS (
SELECT 
     V1.TFC_CODE_I,
     V2.TFC_CODE_E,
     V1.IN_VOYAGE,
     V2.OUT_VOYAGE, 
     V1.VES_TYPE AS VES_TYPE_I,
     V2.VES_TYPE AS VES_TYPE_O,
     I.ITEM_KEY,
     V1.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_I,
     V2.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_E
FROM ITEM_FILTERED I
     LEFT JOIN SCHEMA_NAME.VESSEL_DETAILS V1 ON  V1.TFC_CODE_I = I.ARR_CAR AND V1.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.VESSEL_DETAILS V2 ON V2.TFC_CODE_E = I.DEP_CAR AND V2.OP <> ''d''
),
PREGATE_TRANSACT_FILTERED AS (             
SELECT 
     I.ITEM_KEY,
     CASE WHEN I.ARR_BY = ''P'' AND I.ARR_CAR = PT_STRIP.OPERATION_TYPE THEN PT_STRIP.OPERATION_METHOD 
      WHEN I.ARR_BY = ''P'' AND I.ARR_CAR = PT_STUFF.OPERATION_TYPE THEN PT_STUFF.OPERATION_METHOD
      WHEN I.ARR_BY = ''P'' AND I.ARR_CAR = ISS.OPERATION_TYPE THEN ISS.OPERATION_METHOD
      ELSE PTR.OPERATION_METHOD END AS OPERATION_METHOD_IN,
     CASE WHEN I.DEP_BY = ''P'' AND I.DEP_BY = PT_STRIP.OPERATION_TYPE THEN PT_STRIP.OPERATION_METHOD 
      WHEN I.DEP_BY = ''P'' AND I.DEP_CAR = PT_STUFF.OPERATION_TYPE THEN PT_STUFF.OPERATION_METHOD
      ELSE PTD.OPERATION_METHOD END AS OPERATION_METHOD_OUT,
     PTR.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_IN,
     PTD.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_OUT,
     PT_STRIP.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_STRIP,
     PT_STUFF.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_STUFF,
     ISS.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE_ISS
    FROM ITEM_FILTERED I
     LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PTR ON I.ITEM_KEY = PTR.ITEM_KEY AND PTR.R_D = ''R'' AND PTR.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PTD ON I.ITEM_KEY = PTD.ITEM_KEY AND PTD.R_D = ''D'' AND PTD.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PT_STRIP ON I.ITEM_KEY = PT_STRIP.ITEM_KEY AND PT_STRIP.OPERATION_TYPE = ''STRIP'' AND PT_STRIP.R_D = '' '' AND PT_STRIP.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PT_STUFF ON I.ITEM_KEY = PT_STUFF.ITEM_KEY AND PT_STUFF.OPERATION_TYPE = ''STUFF'' AND PT_STUFF.R_D = '' '' AND PT_STUFF.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.ITEM_STRIP_STUFF ISS ON I.ITEM_KEY = ISS.ITEM_KEY AND ISS.OP <> ''d''
),
ITEM_COMMENTS_FILTERED AS (
SELECT 
     ITEM_KEY, 
     COMMENTS,
     LAST_MODIFIED_DATE
FROM (
     SELECT 
      I.ITEM_KEY,
      IC.COMMENTS,
      ROW_NUMBER() OVER (PARTITION BY I.ITEM_KEY ORDER BY IC.CRT_TS DESC) AS RN,
      IC.LAST_MODIFIED_DATE
     FROM ITEM_FILTERED I 
      JOIN SCHEMA_NAME.ITEM_COMMENTS IC ON IC.ITEM_KEY = I.ITEM_KEY AND IC.OP <> ''d''
) SUB
WHERE RN = 1
),
ITEM_SEAL_FILTERED AS (
    SELECT 
         ITEM_KEY,
         MAX(LOP_SEAL_NO) AS LOP_SEAL_NO,
         MAX(CUST_SEAL_NO) AS CUST_SEAL_NO,
         MAX(KHA_SEAL_NO) AS KHA_SEAL_NO,
         MAX(LOP_LAST_MODIFIED_DATE) AS LOP_LAST_MODIFIED_DATE,
         MAX(CUST_LAST_MODIFIED_DATE) AS CUST_LAST_MODIFIED_DATE,
         MAX(KHA_LAST_MODIFIED_DATE) AS KHA_LAST_MODIFIED_DATE
FROM (
     SELECT
          ITEM_KEY,
          TRIM(CASE WHEN SEAL_TYPE = ''LOP'' THEN SEAL_NO ELSE NULL END) AS LOP_SEAL_NO,
          TRIM(CASE WHEN SEAL_TYPE = ''CUST'' THEN SEAL_NO ELSE NULL END) AS CUST_SEAL_NO,
          TRIM(CASE WHEN SEAL_TYPE = ''KHA'' THEN SEAL_NO ELSE NULL END) AS KHA_SEAL_NO,
          (CASE WHEN SEAL_TYPE = ''LOP'' THEN LAST_MODIFIED_DATE ELSE NULL END) AS LOP_LAST_MODIFIED_DATE,
          (CASE WHEN SEAL_TYPE = ''CUST'' THEN LAST_MODIFIED_DATE ELSE NULL END) AS CUST_LAST_MODIFIED_DATE,
          (CASE WHEN SEAL_TYPE = ''KHA'' THEN LAST_MODIFIED_DATE ELSE NULL END) AS KHA_LAST_MODIFIED_DATE 
 FROM (
      SELECT 
           I.ITEM_KEY, 
           ISL.SEAL_TYPE,
           LISTAGG(ISL.SEAL_NO, '', '') WITHIN GROUP (ORDER BY ISL.SEAL_NO) AS SEAL_NO,
           SEAL_DATE.LAST_MODIFIED_DATE AS LAST_MODIFIED_DATE
      FROM ITEM_FILTERED I 
           JOIN SCHEMA_NAME.ITEM_SEAL ISL ON ISL.ITEM_KEY = I.ITEM_KEY AND ISL.OP <> ''d''
           JOIN (SELECT ITEM_KEY, SEAL_TYPE, LAST_MODIFIED_DATE
                    FROM (
                    SELECT 
                         IFL.ITEM_KEY,
                         SEAL.SEAL_TYPE,
                         SEAL.LAST_MODIFIED_DATE,
                         ROW_NUMBER() OVER (PARTITION BY IFL.ITEM_KEY, SEAL.SEAL_TYPE ORDER BY SEAL.LAST_MODIFIED_DATE DESC) AS RN
                    FROM ITEM_FILTERED IFL 
                    JOIN SCHEMA_NAME.ITEM_SEAL SEAL 
                         ON SEAL.ITEM_KEY = IFL.ITEM_KEY AND SEAL.OP <> ''d''
                    )
               WHERE RN = 1) SEAL_DATE
          ON ISL.ITEM_KEY = SEAL_DATE.ITEM_KEY AND ISL.SEAL_TYPE = SEAL_DATE.SEAL_TYPE
          GROUP BY I.ITEM_KEY, ISL.SEAL_TYPE, SEAL_DATE.LAST_MODIFIED_DATE --SEAL_DATE.OP
          ) SEAL_TYPE
         ) SEAL_LIST
GROUP BY ITEM_KEY
),
ITEM_SPECIAL_HANDLING_FILTERED AS (
    SELECT 
     I.ITEM_KEY, 
     LISTAGG(
      CASE 
           WHEN ISH.CODE <> '' '' AND ISH.DESCRIPTION <> '' '' 
           THEN ISH.CODE || '' - '' || ISH.DESCRIPTION 
       ELSE '''' 
          END, '', '' ) WITHIN GROUP (ORDER BY ISH.CODE) AS ITEM_SPECIAL_HANDLING,
         ISH_OP.LAST_MODIFIED_DATE
FROM ITEM_FILTERED I
 JOIN SCHEMA_NAME.ITEM_SPECIAL_HANDLING ISH ON I.ITEM_KEY = ISH.ITEM_KEY AND ISH.OP <> ''d''
 JOIN ( SELECT ITEM_KEY, LAST_MODIFIED_DATE
       FROM (
        SELECT 
         IFL.ITEM_KEY,
         SH.LAST_MODIFIED_DATE,
         ROW_NUMBER() OVER (PARTITION BY IFL.ITEM_KEY ORDER BY SH.LAST_MODIFIED_DATE DESC) AS RN
        FROM ITEM_FILTERED IFL
        JOIN SCHEMA_NAME.ITEM_SPECIAL_HANDLING SH 
         ON IFL.ITEM_KEY = SH.ITEM_KEY AND SH.OP <> ''d''
       )
       WHERE RN = 1) ISH_OP ON ISH_OP.ITEM_KEY = I.ITEM_KEY
WHERE EXTRACT(YEAR FROM ISH.COMPL_TS) = 1900
    GROUP BY I.ITEM_KEY, ISH_OP.LAST_MODIFIED_DATE --ISH_OP.OP
    ),
    ITEM_STOPS_FILTERED AS (
    SELECT 
         ITEM_KEY,
         STOP_CD,
         STOP_DESC,
         LAST_MODIFIED_DATE
    FROM (
     SELECT 
          I.ITEM_KEY, 
          ISS.STOP_CD, 
          ISS.STOP_DESC,                   
          ROW_NUMBER() OVER (PARTITION BY I.ITEM_KEY ORDER BY ISS.CRT_TS DESC) AS RN,
          ISS.LAST_MODIFIED_DATE
     FROM ITEM_FILTERED I 
          JOIN SCHEMA_NAME.ITEM_STOPS ISS ON I.ITEM_KEY = ISS.ITEM_KEY AND ISS.OP <> ''d''
          LEFT JOIN SCHEMA_NAME.CONFIG_STOPCODE CC ON CC.STOP_CODE = ISS.STOP_CD AND CC.STOP_TYPE = ''STOP''
     WHERE ISS.CLR_BY = '' ''
    ) SUB
WHERE RN = 1
),
ITEM_LOCATION_FILTERED AS (
SELECT 
     I.ITEM_KEY,
     ILC.STACK,
     ILC.X,
     ILC.Y,
     ILC.Z,
     Y.REGION,
     Y.AREA,
     ILC.LAST_MODIFIED_DATE
FROM ITEM_FILTERED I
     JOIN SCHEMA_NAME.ITEM_LOCATION ILC ON I.ITEM_KEY = ILC.ITEM_KEY AND ILC.OP <> ''d''
     LEFT JOIN SCHEMA_NAME.YARD_AREA Y ON ILC.STACK = Y.STACK AND Y.OP <> ''d''
WHERE ILC.STK_PCH = ''C'' 
     AND ILC.EXEC_TS BETWEEN Y.FR_DATE AND Y.TO_DATE
    )
SELECT DISTINCT
    I.ITEM_KEY AS ID_CONT_TOS,
    ''*'' AS VOYAGE_KEY,
    NULL AS BARGE_KEY,
    VS.TFC_CODE_I AS IMPORT_VOYAGE_KEY,
    VS.TFC_CODE_E AS EXPORT_VOYAGE_KEY,
    VS.OUT_VOYAGE AS EXPORT_VOYAGE,
    VS.IN_VOYAGE AS IMPORT_VOYAGE,
    I.BILL_OF_LADING AS BILL_OF_LADING_NO,
    I.BOOK_NO AS BOOKING_NO,
    I.ITEM_NO AS CONTAINER_NO,
    I.CATEGORY AS CLASS_CODE,
    I.LINE_OPER AS OPERATION_CODE,
    I.AGENT AS AGENCY_CODE,
    I.FEL AS FE,
    I.ITEM_TYPE AS CONTAINER_TYPE,
    I.LOCAL_SIZE_TYPE AS LOCAL_SIZE_TYPE,
    NULL AS ISO_SIZE_TYPE,--I.ISO_SIZE_TYPE,
    PT.OPERATION_METHOD_IN AS JOB_MODE_CODE_IN,              
    CASE WHEN VS.VES_TYPE_I = ''B'' THEN ''B''
        ELSE I.ARR_BY END AS METHOD_CODE_IN,
    I.CONSIGNOR AS CUSTOMER_CODE,
    I.ARR_TS AS DATE_IN,
    I.DEP_TS AS DATE_OUT,
    PT.OPERATION_METHOD_OUT AS JOB_MODE_CODE_OUT,
    CASE WHEN VS.VES_TYPE_O = ''B'' THEN ''B''
        ELSE I.DEP_BY END AS METHOD_CODE_OUT,
    IL.STACK AS BLOCK,
    IL.X AS BAY,
    IL.Y AS "ROW",
    IL.Z AS TIER,
    IL.AREA AS AREA,
    IL.REGION, 
    I.TARE AS TARE_WEIGHT,
    ISF.LOP_SEAL_NO AS SEAL_NO,
    ISF.CUST_SEAL_NO AS SEAL_NO_1,
    ISF.KHA_SEAL_NO AS SEAL_NO_2, 
    I.LOAD_PORT AS POL,
    I.DISCH_PORT AS POD,                  
    I.FDISCH_PORT AS FPOD,
    I.LL_DISCH_PORT AS TRANSIT_PORT,
    CASE WHEN STOP.ITEM_KEY IS NOT NULL THEN 1 ELSE 0 END AS TER_HOLD,
    STOP.STOP_DESC AS TER_HOLD_REASON,
    NULL AS LOCAL_FOREIGN,
    I.GRADE AS CONTAINER_CONDITION,
    IC.COMMENTS AS NOTE,
    I.EIR_ID AS EIR_NO,
    ISH.ITEM_SPECIAL_HANDLING AS SPECIAL_NOTE,
    CASE  
     WHEN I.OP = ''d'' THEN ''d''
     WHEN I.OP = ''c'' AND I.LAST_MODIFIED_DATE = GREATEST(NVL(I.LAST_MODIFIED_DATE, TO_TIMESTAMP(TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''), ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(VS.LAST_MODIFIED_DATE_E, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(VS.LAST_MODIFIED_DATE_I, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(IL.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(ISF.LOP_LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(ISF.CUST_LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(ISF.KHA_LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(STOP.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(IC.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(ISH.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(PT.LAST_MODIFIED_DATE_IN, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(PT.LAST_MODIFIED_DATE_OUT, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(PT.LAST_MODIFIED_DATE_STRIP, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(PT.LAST_MODIFIED_DATE_STUFF, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  NVL(PT.LAST_MODIFIED_DATE_ISS, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))) THEN ''c''
     ELSE ''u'' END OP
FROM ITEM_FILTERED I
    LEFT JOIN VESSEL_DETAILS_FILTERED VS ON VS.ITEM_KEY = I.ITEM_KEY
    LEFT JOIN ITEM_LOCATION_FILTERED IL ON I.ITEM_KEY = IL.ITEM_KEY        
    LEFT JOIN ITEM_SEAL_FILTERED ISF ON I.ITEM_KEY = ISF.ITEM_KEY
    LEFT JOIN ITEM_STOPS_FILTERED STOP ON I.ITEM_KEY = STOP.ITEM_KEY
    LEFT JOIN ITEM_COMMENTS_FILTERED IC ON I.ITEM_KEY = IC.ITEM_KEY
    LEFT JOIN ITEM_SPECIAL_HANDLING_FILTERED ISH ON I.ITEM_KEY = ISH.ITEM_KEY        
    LEFT JOIN PREGATE_TRANSACT_FILTERED PT ON I.ITEM_KEY = PT.ITEM_KEY',N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline',N'ID_CONT_TOS'),
	 (N'ecm_container_type',N'SELECT
   CODE_REF as container_type_code,
   DESCR as container_type_name,
   OP
FROM SCHEMA_NAME.SYS_CODES
WHERE CODE_TP = ''CTRTYPE''
AND CODE_REF = ?',N'com.kd.snp.datahub.flink.ContainerTypeAccumulateJobPipeline',N'CONTAINER_TYPE_CODE'),
	 (N'ecm_job',N'SELECT CODE_REF AS job_code,
      LOCAL_DESCR AS job_name_vn,
      NULL AS job_type,
      DESCR AS job_name_en,
      OP
FROM SCHEMA_NAME.SYS_CODES
WHERE CODE_TP = ''OPTYPE''
AND CODE_REF = ?',N'com.kd.snp.datahub.flink.JobAccumulateJobPipeline',N'JOB_CODE'),
	 (N'ecm_job_mode',N'SELECT
   OPERATION_METHOD AS job_mode_code,
   OPERATION_NAME AS job_mode_name,
   OPERATION_TYPE AS job_mode_type,
   OP
FROM SCHEMA_NAME.OPERATION_METHOD
WHERE OPERATION_METHOD = ?',N'com.kd.snp.datahub.flink.JobModeAccumulateJobPipeline',N'JOB_MODE_CODE'),
	 (N'ecm_method',N'SELECT
   CODE_REF as method_code,
   DESCR as method_name,
   OP
FROM SCHEMA_NAME.SYS_CODES
WHERE CODE_TP = ''CARTYPE''
   AND CODE_REF = ?',N'com.kd.snp.datahub.flink.MethodAccumulateJobPipeline',N'METHOD_CODE'),
	 (N'ecm_operation',N'SELECT
   LINE_OPER AS operation_code,
   FULL_NAME AS operation_name,
   NULL AS payment_type,
   EXPIRE_FLG AS is_active,
   OP
FROM SCHEMA_NAME.LINE_OPER
WHERE LINE_OPER = ?',N'com.kd.snp.datahub.flink.OperationAccumulateJobPipeline',N'OPERATION_CODE');
INSERT INTO dbo.configuration_accumulate (kafka_topic,accumulate_view_query,job_name,accumulate_key) VALUES
	 (N'ecm_reefer_container',N'SELECT								 
	''*'' AS voyage_key,
	I.ITEM_NO AS container_no,
	I.CATEGORY AS class_code,
	CASE WHEN IR.SETTING_TEMP = 9999 THEN NULL ELSE IR.SETTING_TEMP END AS temperature,
	IR.VENT_VOLUMETRIC_RATE AS vent,
	IR.VENT_VOLUMETRIC_UNIT AS unit_of_vent,
	IR.PLUG_TS AS plugin_date,
	IR.UNPLUG_TS AS unplugin_date,
	PT.REFEER_EXPIRY_TS AS expire_of_plugin_date,
	CASE WHEN IR.INGATE_TEMP = 9999 THEN NULL ELSE IR.INGATE_TEMP END temperature_in,
	CASE WHEN IR.OUTGATE_TEMP = 9999 THEN NULL ELSE IR.OUTGATE_TEMP END temperature_out,
	IR.ITEM_KEY AS id_cont_tos,
	IPR.REMARKS AS pti_note,
	CASE WHEN ir.op = ''d'' THEN ''d''
        WHEN ir.op = ''c'' AND ir.LAST_MODIFIED_DATE = greatest(COALESCE(ir.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                                                             COALESCE(i.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                                                              COALESCE(pt.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                                                              COALESCE(ipr.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))
                                                             ) then ''c''
        else ''u'' end op
FROM SCHEMA_NAME.ITEM_REEFER IR
	JOIN SCHEMA_NAME.ITEM I ON IR.ITEM_KEY = I.ITEM_KEY AND I.FEL = ''E''
	LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PT ON I.ITEM_KEY = PT.ITEM_KEY AND PT.R_D = ''D''
	LEFT JOIN (SELECT ITEM_KEY, REMARKS, LAST_MODIFIED_DATE 
				FROM (SELECT 
						IP.ITEM_KEY,
						IP.REMARKS,
						ip.LAST_MODIFIED_DATE,
						ROW_NUMBER() OVER (PARTITION BY IP.ITEM_KEY ORDER BY IP.PTI_COMPLETE_DATE DESC) AS RN
					FROM SCHEMA_NAME.ITEM_PTI IP ) SUB
				WHERE RN = 1) IPR ON IPR.ITEM_KEY = IR.ITEM_KEY 
	WHERE IR.ITEM_KEY = ?',N'com.kd.snp.datahub.flink.ReeferContainerAccumulateJobPipeline',N'ID_CONT_TOS'),
	 (N'ecm_vessel_schedule',N'SELECT 
    TRIM(vd.VES_ID) AS VOYAGE_KEY,
    TRIM(vd.VES_CD) AS VESSEL_CODE,
    TRIM(vd.TFC_CODE_I) AS IMPORT_VOYAGE_KEY,
    TRIM(vd.TFC_CODE_E) AS EXPORT_VOYAGE_KEY,
    TRIM(vd.VES_SERVICE) AS LANE_CODE,
    CASE WHEN EXTRACT(YEAR FROM vd.TCA_CUTOFF_TS) = 1900 THEN NULL ELSE vd.TCA_CUTOFF_TS END AS PORT_COT,
    CASE WHEN EXTRACT(YEAR FROM vd.ICD_CUTOFF_TS) = 1900 THEN NULL ELSE vd.ICD_CUTOFF_TS END AS ICD_COT,
    CASE WHEN EXTRACT(YEAR FROM vd.EST_BERTH_TS) = 1900 THEN NULL ELSE vd.EST_BERTH_TS END AS ETA,
    CASE WHEN EXTRACT(YEAR FROM vd.EST_BERTH_TS) = 1900 THEN NULL ELSE vd.EST_BERTH_TS END AS ETB,
    CASE WHEN EXTRACT(YEAR FROM vd.EST_DEP_TS) = 1900 THEN NULL ELSE vd.EST_DEP_TS END AS ETD,
    CASE WHEN EXTRACT(YEAR FROM vd.ACT_PILOT_TS) = 1900 THEN NULL ELSE vd.ACT_PILOT_TS END AS ATA,
    CASE WHEN EXTRACT(YEAR FROM vd.ACT_BERTH_TS) = 1900 THEN NULL ELSE vd.ACT_BERTH_TS END AS ATB,
    CASE WHEN EXTRACT(YEAR FROM vd.ACT_DEP_TS) = 1900 THEN NULL ELSE vd.ACT_DEP_TS END AS ATD,
    NULL AS OTHER_SHIP,
    CASE WHEN vd.VES_TYPE = ''B'' THEN 1 ELSE 0 END AS BARGE_CHECK,
    vd.REMARKS AS NOTE,
    vd.YEAR_VOYAGE AS VESSEL_YEAR,
    vd.IN_VOYAGE AS IN_VOYAGE,
    vd.OUT_VOYAGE AS OUT_VOYAGE,
    vd.OP
FROM SCHEMA_NAME.VESSEL_DETAILS vd
WHERE vd.VES_ID = ?',N'com.kd.snp.datahub.flink.VesselScheduleAccumulateJobPipeline',N'VOYAGE_KEY'),
	 (N'ecm_container_condition',N'SELECT
    ''*'' AS OPERATION_CODE,
    CODE_REF AS CONTAINER_CONDITION,
    DESCR AS CONTAINER_CONDITION_NAME_EN,
    NULL AS IS_DAMAGE,
    LOCAL_DESCR AS CONTAINER_CONDITION_NAME_VN,
    OP
FROM SCHEMA_NAME.SYS_CODES
WHERE CODE_TP = ''GRADE''
  AND CODE_REF = ?',N'com.kd.snp.datahub.flink.ContainerConditionAccumulateJobPipeline',N'CONTAINER_CONDITION'),
	 (N'ecm_damage_code',N'SELECT 
    DAMAGE_CD as damage_code, 
    DESCR_VI as damage_description_vn, 
    DESCR_EN as damage_description_en,
    OP
from SCHEMA_NAME.DAMAGE_CODE
where DAMAGE_CD = ?',N'com.kd.snp.datahub.flink.DamageCodeAccumulateJobPipeline',N'DAMAGE_CODE'),
	 (N'ecm_vendor',N'SELECT 
    CODE_REF as vendor_code,
    DESCR as vendor_name,
    null as note,
    OP
FROM SCHEMA_NAME.SYS_CODES
WHERE CODE_TP = ''VSSCPROV'' 
AND CODE_REF = ?',N'com.kd.snp.datahub.flink.VendorAccumulateJobPipeline',N'VENDOR_CODE'),
	 (N'ecm_seal_management',N'SELECT 
    LINEOPER AS operation_code,
    SEALFORMAT AS serial_no,
    QUANTITY_RECEIVE AS total_seal,
    FROMNUMBER AS from_seal,
    TONUMBER AS to_seal,
    DESCR AS note,
    OP
FROM SCHEMA_NAME.SEAL_MANAGEMENT_MASTER
WHERE SEALFORMAT = ?',N'com.kd.snp.datahub.flink.SealManagementAccumulateJobPipeline',N'SERIAL_NO'),
	 (N'ecm_customer',N'SELECT 
     CUST_TYPE AS customer_type_code,
     CUST_REG_NO AS customer_code,
     FULL_NAME AS customer_name,
     ADDR1 AS address,
     TAX_FILE_NO AS vat,
     email,
     '''' AS representative,
     MOBILE AS phone,
     CUST_GROUP AS customer_level_code,
     CASE WHEN STOP_YN = ''Y'' THEN 1 ELSE 0 END AS is_active,
     OP
FROM SCHEMA_NAME.CUSTOMER
WHERE CUST_REG_NO = ?',N'com.kd.snp.datahub.flink.CustomerAccumulateJobPipeline',N'CUSTOMER_CODE'),
	 (N'ecm_gate',N'SELECT
    GN.OWNER AS GATE_OWNER,
    GN.GATE_NO AS GATE_CONTRACT_CODE,
    NULL AS GATE_TYPE,
    GL.LANE_NO AS GATE_CODE,
    GL.DESCR AS GATE_NAME,
    NULL AS NOTE,
    CASE
        WHEN GN.OP = ''d'' THEN ''d''
        WHEN GN.OP = ''c'' AND GN.LAST_MODIFIED_DATE = GREATEST(
                COALESCE(GN.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                COALESCE(GL.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))
                                                     ) THEN ''C''
        ELSE ''U''
        END AS OP
FROM SCHEMA_NAME.GATE_NO_INFO GN
         JOIN SCHEMA_NAME.GATE_LANE_INFO GL ON GN.GATE_NO = GL.GATE_NO
WHERE GN.VIRTUAL_FLG <> ''Y''
  AND GN.GATE_NO = ?',N'com.kd.snp.datahub.flink.GateAccumulateJobPipeline',N'GATE_CONTRACT_CODE'),
	 (N'ecm_vessel',N'SELECT 
    VES_TYPE AS vessel_type, 
	VES_CD AS vessel_code, 
	VES_NAME AS vessel_name, 
	LINE_OPER AS operation_code, 
	REG_FLG AS national, 
	CALL_SIGN AS call_sign, 
	LLOYDS_NO AS imo, 
	DWT AS dwt, 
	GROSS_TONS AS grt, 
	VES_LEN AS loa, 
	BEAM AS lbp, 
	MAX_DRAFT as max_draft, 
	HOLDS AS hold, 
	REMARKS AS note,
	OP
FROM SCHEMA_NAME.VESSELS
WHERE VES_CD = ?',N'com.kd.snp.datahub.flink.VesselAccumulateJobPipeline',N'VESSEL_CODE'),
	 (N'ecm_special_handling',N'SELECT 
    SPECIAL_HDL_CODE as special_handling_code,
    SPECIAL_HDL_DESC as special_handling_description, 
    SPECIAL_HDL_ACTIVITY as note,
    OP
FROM SCHEMA_NAME.SPECIAL_HDL_CODE
WHERE SPECIAL_HDL_CODE = ?',N'com.kd.snp.datahub.flink.SpecialHandlingAccumulateJobPipeline',N'SPECIAL_HANDLING_CODE');
INSERT INTO dbo.configuration_accumulate (kafka_topic,accumulate_view_query,job_name,accumulate_key) VALUES
	 (N'ecm_container_spec',N'SELECT     
    ITEM_NO as container_no,
    null as operation_code,
    ISO as local_size_type,
    null as iso_size_type,
    TARE_WEIGHT as tare_weight,
    MAX_GROSS_WEIGHT as max_gross_weight,
    null as container_type,
    PRODUCED_TS as container_age,
    REEFER_PRODUCED_TS as machine_age,
    REEFER_MODEL as manufacturer,
    null as machine_version,
    null as container_capacity,
    REMARK as note,
    OP
from SCHEMA_NAME.CONTAINER_STRUCTURE 
where ITEM_NO = ?',N'com.kd.snp.datahub.flink.ContainerSpecAccumulateJobPipeline',N'CONTAINER_NO'),
	 (N'ecm_yard',N'SELECT 
       YA.MANAGE_BY AS MANAGE_BY,
       YA.REGION AS REGION, 
       CASE WHEN YA.IS_VIRTUAL_HEAP_STACK = ''Y'' THEN 1 ELSE 0 END AS YARD_TYPE, 
       YA.AREA AS AREA,
       SC.DESCR AS YARD_NAME, 
       YA.MAX_TEU AS CAPACITY,
       '''' AS EQUIPMENT_TYPE,
       YA.STACK AS BLOCK,
       YA.X1 AS FROM_BAY,
       YA.X2 AS TO_BAY,
       NULL AS USE_RATE,
       (CASE WHEN YA.TO_DATE < CURRENT_DATE THEN 0 ELSE 1 END) AS IS_ACTIVE,
       YA.OP
FROM SCHEMA_NAME.YARD_AREA YA
       LEFT JOIN SCHEMA_NAME.SYS_CODES SC ON SC.CODE_TP =''YARDAREA'' AND YA.AREA = SC.CODE_REF
WHERE YA.STACK = ? 
    AND YA.MANAGE_BY IS NOT NULL
    AND YA.REGION != '' ''
    AND YA.AREA != '' ''
    AND YA.STACK != '' ''',N'com.kd.snp.datahub.flink.YardAccumulateJobPipeline',N'BLOCK'),
	 (N'ecm_equipment',N'SELECT 
    c.CHE_TYPE AS equipment_type,
    s.DESCR AS equipment_type_name,
    CASE WHEN trim(c.internal_che_id) <> '''' THEN c.internal_che_id ELSE c.che_id END AS equipment_code,
    NULL AS equipment_name,
    NULL AS serial_no,
    NULL AS install_date,
    NULL AS expire_date,
    NULL AS start_date,
    case when trim(c.internal_che_id) <> '''' then ''ON'' else ''OFF'' end as status,
    NULL AS productivity,
    NULL AS maxjob,
    NULL AS location,
    NULL AS area,
    c.REMARKS AS note,
    c.OP AS op
FROM SCHEMA_NAME.CHE_MASTER c
   JOIN SCHEMA_NAME.SYS_CODES s ON c.CHE_TYPE = s.CODE_REF AND s.CODE_TP = ''CHETYPE'' AND c.CHE_TYPE <> ''TLR''
WHERE c.CHE_ID = ?',N'com.kd.snp.datahub.flink.EquipmentAccumulateJobPipeline',N'EQUIPMENT_CODE'),
	 (N'ecm_booking',N'SELECT  
	RC.RAC_KEY AS RAC_KEY
	,(CASE WHEN RM.RA_KEY IS NOT NULL THEN 0 ELSE 1 END) AS BOOKING_TYPE
    ,RC.BOOKING_NO AS BOOKING_NO
    ,(CASE WHEN RM.RA_KEY IS NOT NULL THEN RM.RA_DT ELSE RS.RECEIVE_TS END) AS BOOKING_DATE
    ,(CASE WHEN RM.RA_KEY IS NOT NULL THEN RM.RA_EXPIRY_DT ELSE RS.RA_EXPIRY_DT END) AS EXPIRE_DATE
    ,RC.LINE_OPER AS OPERATION_CODE
    ,NULL AS ISO_SIZE_TYPE
    ,(CASE WHEN RM.RA_KEY IS NOT NULL THEN RM.ISO_CODE ELSE RS.ISO END) AS LOCAL_SIZE_TYPE
    ,NVL(RM.CTR_QUANTITY, 0) AS BOOKING_AMOUNT
    ,NVL(RM.CTR_DELIVERED_QTY, 0) AS STACKING_AMOUNT
    ,RS.ITEM_NO AS CONTAINER_NO
    ,RC.VES_NAME
    ,RC.DISCHARGE_VOY_NO AS IMPORT_VOYAGE
    ,RC.OUT_VOYAGE AS EXPORT_VOYAGE
    ,RC.POL AS POL
    ,RC.POD AS POD   
    ,RC.FPD AS FPOD
    ,(CASE WHEN RM.DELETED_FLG = 1 THEN 2 
     WHEN RM.CTR_DELIVERED_QTY = 0 THEN 0 
     WHEN RM.CTR_DELIVERED_QTY < RM.CTR_QUANTITY THEN 1
     ELSE 3 END) AS BOOKING_STATUS
    ,NULL AS CONTAINER_CLASSIFY_CODE
    ,RC.REMARK AS NOTE
    ,(CASE WHEN RM.RA_KEY IS NOT NULL THEN RM.SPECIAL_REMARK ELSE RS.SPECIAL_REMARK END) AS BOOKING_RELEASE_NOTE
    ,(CASE WHEN RC.OP = ''d'' THEN ''d''
 WHEN RC.OP = ''c'' AND RC.LAST_MODIFIED_DATE = GREATEST(COALESCE(RC.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
              COALESCE(RM.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
              COALESCE(RS.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))) THEN ''c''
 ELSE ''u'' END) OP
FROM SCHEMA_NAME.RA_COMMON RC
    LEFT JOIN SCHEMA_NAME.RA_MTY RM ON RC.RAC_KEY = RM.RAC_KEY AND RM.OP <> ''d''
        LEFT JOIN SCHEMA_NAME.RA_SPECIFIC_CTRS RS ON RS.RAC_KEY = RC.RAC_KEY AND RS.OP <> ''d''
WHERE RC.RAC_KEY = ? AND ( RM.RA_KEY IS NOT NULL OR RS.RA_KEY IS NOT NULL)',N'com.kd.snp.datahub.flink.BookingAccumulateJobPipeline',N'RAC_KEY'),
	 (N'ecm_gate_job',N'SELECT 
        VD.VES_ID AS VOYAGE_KEY
        ,VD.IN_VOYAGE AS IMPORT_VOYAGE
        ,VD.OUT_VOYAGE AS EXPORT_VOYAGE
        ,PT.OPERATION_METHOD AS JOB_MODE_CODE
        ,TT.EIR_ID AS EIR_NO
        ,TT.CRT_TS AS ISSUE_DATE
        ,PT.LINER_EXPIRY_TS AS EXPIRE_DATE
        ,PT.REFEER_EXPIRY_TS AS EXPIRE_PLUGIN_DATE
        ,NULL AS DELIVERY_ORDER
        ,TRIM(PT.BILL_OF_LADING) AS BILL_OF_LADING_NO
        ,(CASE WHEN TRIM(PT.BILL_OF_LADING) <> '' THEN PT.BILL_OF_LADING 
         ELSE I.BILL_OF_LADING END) AS BILL_OF_LADING_NO
        ,(CASE WHEN TRIM(PT.BOOK_NO) <> '' THEN PT.BOOK_NO 
         ELSE I.BOOK_NO END) AS BOOKING_NO
        ,I.ITEM_NO AS CONTAINER_NO
        ,I.CATEGORY AS CLASS_CODE
        ,PT.LINE_OPER AS OPERATION_CODE
        ,PT.FEL AS FE
        ,PT.CTR_TYPE AS CONTAINER_TYPE
        ,PT.ISO_CODE AS LOCAL_SIZE_TYPE
        ,I.LOAD_PORT AS POL
        ,I.DISCH_PORT AS POD
        ,I.FDISCH_PORT AS FPOD
        ,NULL AS TRANSIT_CODE
        ,I.LL_DISCH_PORT AS TRANSIT_PORT
        ,NULL AS EMPTY_RETURN_LOCATION
        ,NULL AS SHIPPER_NAME
        ,(CASE WHEN VD.VES_TYPE = ''B'' THEN ''B'' 
         WHEN (PT.R_D = ''R'' AND I.ARR_BY = ''T'') OR (PT.R_D = ''D'' AND I.DEP_BY = ''T'') THEN ''T''
         ELSE NULL END) AS IS_TRUCK_BARGE
        ,I.ARR_CAR AS TRUCK_NO    
        ,NULL AS REMOOC_NO
        ,(CASE WHEN TT.R_D = ''R'' THEN ''I'' ELSE ''O'' END) GATE_PURPOSE
        ,GL_I.GATE_NO AS GATE_IN_NAME
        ,GL_O.GATE_NO AS GATE_OUT_NAME
        ,T.IG_TS AS TIME_IN
        ,T.OG_TS AS TIME_OUT
        ,PT.REMARKS AS NOTE
        ,I.GRADE AS CONTAINER_CONDITION
        ,TT.ITEM_KEY AS ID_CONT_TOS
        ,(CASE WHEN TT.OP = ''d'' THEN ''d''
 WHEN TT.OP = ''c'' AND TT.LAST_MODIFIED_DATE = GREATEST(COALESCE(TT.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(PT.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(I.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(T.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(GL_I.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(GL_O.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                 COALESCE(VD.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))) THEN ''c''
 ELSE ''u'' END) OP
FROM SCHEMA_NAME.TRK_TRANSACT TT
    INNER JOIN SCHEMA_NAME.PREGATE_TRANSACT PT ON PT.EIR_ID = TT.EIR_ID AND PT.OP <> ''d''
    INNER JOIN SCHEMA_NAME.ITEM I ON I.ITEM_KEY = TT.ITEM_KEY AND I.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.TRUCK T ON T.TRK_KEY = TT.TRK_KEY AND T.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.GATE_LANE_INFO GL_I ON T.LANE_NO_IN = GL_I.LANE_NO AND GL_I.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.GATE_LANE_INFO GL_O ON T.LANE_NO_OUT = GL_O.LANE_NO AND GL_O.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.VESSEL_DETAILS VD ON (VD.TFC_CODE_E = I.DEP_CAR OR VD.TFC_CODE_I = I.ARR_CAR) AND VD.OP <> ''d''
WHERE TT.EIR_ID = ? AND
    I.FEL = ''E''',N'com.kd.snp.datahub.flink.GateJobAccumulateJobPipeline',N'EIR_NO'),
	 (N'ecm_yard_job',N'SELECT 
    ''NULL'' AS JOB_MODE_CODE,
    NULL AS EIR_SRV_NO,
    I.ITEM_NO AS CONTAINER_NO,
    I.CATEGORY AS CLASS_CODE,
    I.LINE_OPER AS OPERATION_CODE,
    I.FEL AS FE,
    I.ITEM_TYPE AS CONTAINER_TYPE,
    I.ISO AS LOCAL_SIZE_TYPE,
    IL.CRT_TS AS CREATE_DATE,
    IL.EXEC_TS AS FINISH_DATE,
    NULL AS YARD_JOB,
    IL.STK_CLASS AS STACK_CLASS,
    IL.MOVE_TYPE AS MOVE_TYPE,
    IL.CHE_ID AS EQU_YARD,
    IL.STACK AS BLOCK,
    IL.X AS BAY,
    IL.Y AS "ROW",
    IL.Z AS TIER,
    Y.AREA AS AREA,
    I.ITEM_KEY AS ID_CONT_TOS,
    IL.INTERNAL_MOVE_CD MOVE_REASON_CD,
    CASE WHEN I.OP = ''d'' THEN ''d''
     WHEN I.OP = ''c'' AND I.LAST_MODIFIED_DATE  = GREATEST(COALESCE(I.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                   COALESCE(IL.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                   COALESCE(Y.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))
                    ) THEN ''c''
     ELSE ''u'' END AS OP
FROM TOPOVN_TCCL.ITEM I
    JOIN TOPOVN_TCCL.ITEM_LOCATION IL ON I.ITEM_KEY = IL.ITEM_KEY AND IL.STK_REF IN (''YARD'', ''TRAILER'') AND IL.OP <> ''d''  
    LEFT JOIN TOPOVN_TCCL.YARD_AREA Y ON Y.STACK = IL.STACK AND IL.EXEC_TS BETWEEN Y.FR_DATE AND Y.TO_DATE AND Y.OP <> ''d''
WHERE I.ITEM_KEY = ?',N'com.kd.snp.datahub.flink.YardJobAccumulateJobPipeline',N'ID_CONT_TOS'),
	 (N'ecm_size_type',N'SELECT 
    C2.LINE_OPER AS operation_code,
    C1.ISO AS local_size_type, 
    C2.ISO AS iso_size_type,
    C1.OP 
FROM SCHEMA_NAME.CONVERT_TO_ISO C1 
       LEFT JOIN SCHEMA_NAME.CONVERT_ISO C2 ON C1.ISO = C2.ORIGINAL_ISO
WHERE C1.ISO = ?',N'com.kd.snp.datahub.flink.SizeTypeAccumulateJobPipeline',N'LOCAL_SIZE_TYPE'),
	 (N'ecm_service_order',N'SELECT 
		M1.REG_ID AS REG_ID,
        CC.TRANSPORT_TYPE AS IS_TRUCK_BARGE,
        M1.OPERATION_METHOD AS JOB_MODE_CODE,
        M1.ORDER_NO AS TRANSFER_NO,
        M1.REG_TS AS ISSUE_DATE,
        PT.LINER_EXPIRY_TS AS EXPIRE_DATE,
        PT.REFEER_EXPIRY_TS AS EXPIRE_PLUGIN_DATE,
        (CASE WHEN TRIM(I.BILL_OF_LADING) <> '''' THEN I.BILL_OF_LADING ELSE PT.BILL_OF_LADING END) AS BILL_OF_LADING_NO,
        (CASE WHEN TRIM(I.BOOK_NO) <> '''' THEN I.BOOK_NO ELSE PT.BOOK_NO END) AS BOOKING_NO,
        M2.CTNR_NO AS CONTAINER_NO,
        I.CATEGORY AS CLASS_CODE,
        M2.LINER AS OPERATION_CODE,
        I.FEL AS FE,
        I.ITEM_TYPE AS CONTAINER_TYPE,
        M2.ISO AS LOCAL_SIZE_TYPE,
        NULL AS ISO_SIZE_TYPE,
        M1.PLACE_OF_RECEIPT AS FROM_PLACE,
        M1.PLACE_OF_DELIVERY AS TO_PLACE,
        M1.CUS_REG_NO AS CUSTOMER_CODE,
        M1.REMARKS AS NOTE,
        M2.EIR_ID AS EIR_NO,
        M2.IS_COMPLETED AS IS_FINISH,
        M2.COMPLETED_TS AS FINISH_DATE,
        M2.ITEM_KEY AS ID_CONT_TOS,
        (CASE WHEN M1.OP = ''d'' THEN ''d'' 
     WHEN M1.OP = ''c'' AND M1.LAST_MODIFIED_DATE = GREATEST(COALESCE(M1.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  COALESCE(M2.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  COALESCE(OM.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')), 
                  COALESCE(CC.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  COALESCE(I.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                  COALESCE(PT.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))) THEN ''c''
     ELSE ''u'' END) AS OP              
FROM SCHEMA_NAME.CTNR_MOVE_REG_MASTER M1 
    JOIN SCHEMA_NAME.CTNR_MOVE_REG_DETAILS M2 ON M1.REG_ID = M2.REG_ID AND M2.OP <> ''d''
    JOIN SCHEMA_NAME.ITEM I ON I.ITEM_KEY = M2.ITEM_KEY AND I.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT PT ON M2.EIR_ID = PT.EIR_ID AND PT.OP <> ''d''
    JOIN SCHEMA_NAME.OPERATION_METHOD OM ON M1.OPERATION_METHOD = OM.OPERATION_METHOD AND OM.OP <> ''d''
    JOIN SCHEMA_NAME.CHARGE_CODES CC ON CC.CHARGE_CD = OM.CHARGE_CD AND CC.OP <> ''d''
WHERE M1.REG_ID = ? 
    AND I.FEL = ''E''',N'com.kd.snp.datahub.flink.ServiceOrderAccumulateJobPipeline',N'REG_ID'),
	 (N'ecm_quay_job',N'SELECT 
        IL.STK_REF AS VOYAGE_KEY
        ,IL.ITEM_KEY AS ID_CONT_TOS
        ,VD.IN_VOYAGE AS IMPORT_VOYAGE
        ,VD.OUT_VOYAGE AS EXPORT_VOYAGE
        ,RT.OPERATION_METHOD AS JOB_MODE_CODE
        ,I.ITEM_NO AS CONTAINER_NO
        ,I.CATEGORY AS CLASS_CODE
        ,I.LINE_OPER AS OPERATION_CODE
        ,I.FEL AS FE
        ,I.ITEM_TYPE AS CONTAINER_TYPE
        ,I.ISO AS LOCAL_SIZE_TYPE
        ,IL.CRT_TS AS CREATE_DATE
        ,I.DEP_TS
        ,IL.EXEC_TS AS FINISH_DATE            
        ,(CASE WHEN TRIM(IL.MOVE_TYPE) IN (''06'', ''09'', ''13'', ''10'') THEN ''LD'' 
         WHEN TRIM(IL.MOVE_TYPE) = '''' THEN ''DC''
         ELSE '''' END) AS QUAY_JOB
        ,IL.CHE_ID AS EQU_QUAY
        ,I.LOAD_PORT AS POL
        ,I.DISCH_PORT AS POD
        ,I.FDISCH_PORT AS FPOD
        ,I.LL_DISCH_PORT AS TRANSIT_PORT
        ,RT.REMARKS AS NOTE
        ,(CASE WHEN IL.OP = ''d'' THEN ''d''
 WHEN IL.OP = ''c'' AND IL.LAST_MODIFIED_DATE = GREATEST(COALESCE(IL.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                COALESCE(I.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                COALESCE(RT.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS'')),
                COALESCE(VD.LAST_MODIFIED_DATE, TO_TIMESTAMP(''1900-01-01 12:00:00'', ''YYYY-MM-DD HH24:MI:SS''))) THEN ''c'' 
 ELSE ''u'' END) AS OP
FROM SCHEMA_NAME.ITEM_LOCATION IL
    JOIN SCHEMA_NAME.ITEM I ON IL.ITEM_KEY = I.ITEM_KEY AND IL.STK_CLASS = ''V'' AND I.FEL = ''E'' AND I.OP <> ''d''
    JOIN SCHEMA_NAME.VESSEL_DETAILS VD ON IL.STK_REF = VD.VES_ID AND VD.IN_VOYAGE <> '' '' AND VD.OUT_VOYAGE <> '' '' AND VD.OP <> ''d''
    LEFT JOIN SCHEMA_NAME.PREGATE_TRANSACT RT ON IL.ITEM_KEY = RT.ITEM_KEY AND RT.OP <> ''d''         
WHERE IL.ITEM_KEY = ?',N'com.kd.snp.datahub.flink.QuayJobAccumulateJobPipeline',N'ID_CONT_TOS');
