-- Create table query_data_mapping --
create table query_data_mapping
(
    id               INT IDENTITY(1,1) NOT NULL,
    source_schema    VARCHAR(100) NULL,
    source_table     VARCHAR(100) NULL,
    source_table_key VARCHAR(100) NULL,
    key_priority_no  INT NOT NULL,
    job_name         VARCHAR(255) NULL,
    CONSTRAINT PK_QUERY_DATA_MAPPING PRIMARY KEY (id)
);

-- Data for query_data_mapping table --
insert into dbo.query_data_mapping (source_schema, source_table, source_table_key, key_priority_no, job_name)
values  (N'TOPOVN_TCCL', N'CONVERT_TO_ISO', N'ISO', 1, N'com.kd.snp.datahub.flink.SizeTypeAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CONVERT_ISO', N'ORIGINAL_ISO', 1, N'com.kd.snp.datahub.flink.SizeTypeAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'VES_SERVICE', N'VES_SERVICE', 1, N'com.kd.snp.datahub.flink.VesselLaneAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'AGENT', N'AGENT', 1, N'com.kd.snp.datahub.flink.AgentAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.ClassAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.ContainerTypeAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.JobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'OPERATION_METHOD', N'OPERATION_METHOD', 1, N'com.kd.snp.datahub.flink.JobModeAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_LOCATION', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'PREGATE_TRANSACT', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_COMMENTS', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_SEAL', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_SPECIAL_HANDLING', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_STOPS', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.MethodAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'LINE_OPER', N'LINE_OPER', 1, N'com.kd.snp.datahub.flink.OperationAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'PORTCODE', N'PORT', 1, N'com.kd.snp.datahub.flink.PortAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'VESSEL_DETAILS', N'VES_ID', 1, N'com.kd.snp.datahub.flink.VesselScheduleAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CUSTOMER', N'CUST_REG_NO', 1, N'com.kd.snp.datahub.flink.CustomerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'GATE_NO_INFO', N'GATE_NO', 1, N'com.kd.snp.datahub.flink.GateAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'GATE_LANE_INFO', N'GATE_NO', 1, N'com.kd.snp.datahub.flink.GateAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.ContainerConditionAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ReeferContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_REEFER', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ReeferContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_PTI', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ReeferContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'PREGATE_TRANSACT', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.ReeferContainerAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'VESSELS', N'VES_CD', 1, N'com.kd.snp.datahub.flink.VesselAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'DAMAGE_CODE', N'DAMAGE_CD', 1, N'com.kd.snp.datahub.flink.DamageCodeAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SYS_CODES', N'CODE_REF', 1, N'com.kd.snp.datahub.flink.VendorAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SEAL_MANAGEMENT_MASTER', N'SEALFORMAT', 1, N'com.kd.snp.datahub.flink.SealManagementAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'SPECIAL_HDL_CODE', N'SPECIAL_HDL_CODE', 1, N'com.kd.snp.datahub.flink.SpecialHandlingAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CONTAINER_STRUCTURE', N'ITEM_NO', 1, N'com.kd.snp.datahub.flink.ContainerSpecAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'YARD_AREA', N'STACK', 1, N'com.kd.snp.datahub.flink.YardAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CHE_MASTER', N'CHE_ID', 1, N'com.kd.snp.datahub.flink.EquipmentAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'RA_COMMON', N'RAC_KEY', 1, N'com.kd.snp.datahub.flink.BookingAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'RA_MTY', N'RAC_KEY', 1, N'com.kd.snp.datahub.flink.BookingAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'RA_SPECIFIC_CTRS', N'RAC_KEY', 1, N'com.kd.snp.datahub.flink.BookingAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'PREGATE_TRANSACT', N'EIR_ID', 1, N'com.kd.snp.datahub.flink.GateJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'TRK_TRANSACT', N'EIR_ID', 1, N'com.kd.snp.datahub.flink.GateJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.QuayJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_LOCATION', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.QuayJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'PREGATE_TRANSACT', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.QuayJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.YardJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'ITEM_LOCATION', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.YardJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CTNR_MOVE_REG_DETAILS', N'ITEM_KEY', 1, N'com.kd.snp.datahub.flink.YardJobAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CTNR_MOVE_REG_MASTER', N'REG_ID', 1, N'com.kd.snp.datahub.flink.ServiceOrderAccumulateJobPipeline'),
        (N'TOPOVN_TCCL', N'CTNR_MOVE_REG_DETAILS', N'REG_ID', 1, N'com.kd.snp.datahub.flink.ServiceOrderAccumulateJobPipeline');