-- Create table topic_schema --
create table topic_schema
(
    id              INT IDENTITY(1,1) NOT NULL,
    topic_name      VARCHAR(255) NULL,
    schema_name     VARCHAR(60) NULL,
    table_name      VARCHAR(60) NULL,
    active          BIT NOT NULL,
    reference_table VARCHAR(255) NULL,
    table_key       TEXT NULL,
    CONSTRAINT PK_TOPIC_SCHEMA PRIMARY KEY (id)
);

-- Data for topic_schema table --

insert into dbo.topic_schema (topic_name, schema_name, table_name, active, reference_table, table_key)
values  (N'kafka-topic-prefix.TOPOVN.AGENT', N'TOPOVN_TCCL', N'AGENT', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.ITEM_REEFER', N'TOPOVN_TCCL', N'ITEM_REEFER', 1, null, null),
        (N'ecm_agent', N'ECM', N'AGENT', 1, N'TOPOVN_TCCL.AGENT', N'AGENT'),
        (N'kafka-prefix.TOPOVN.ITEM_PTI', N'TOPOVN_TCCL', N'ITEM_PTI', 1, null, null),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM', N'TOPOVN_TCCL', N'ITEM', 1, null, null),
        (N'TOPOVN_TCCL_G2.TOPOVN.PREGATE_TRANSACT', N'TOPOVN_TCCL', N'PREGATE_TRANSACT', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.SYS_CODES', N'TOPOVN_TCCL', N'SYS_CODES', 1, null, null),
        (N'TOPOVN_TCCL_G1.CHARGE_CODES', N'TOPOVN_TCCL', N'CHARGE_CODES', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.OPERATION_METHOD', N'TOPOVN_TCCL', N'OPERATION_METHOD', 1, null, null),
        (N'TOPOVN_TCCL_G2.TOPOVN.VESSEL_DETAILS', N'TOPOVN_TCCL', N'VESSEL_DETAILS', 1, null, null),
        (N'TOPOVN.ITEM_COMMENTS', N'TOPOVN_TCCL', N'ITEM_COMMENTS', 1, null, null),
        (N'TOPOVN.ITEM_SEAL', N'TOPOVN_TCCL', N'ITEM_SEAL', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.ITEM_SPECIAL_HANDLING', N'TOPOVN_TCCL', N'ITEM_SPECIAL_HANDLING', 1, null, null),
        (N'TOPOVN_TCCL_G2.TOPOVN.ITEM_STOPS', N'TOPOVN_TCCL', N'ITEM_STOPS', 1, null, null),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM_LOCATION', N'TOPOVN_TCCL', N'ITEM_LOCATION', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.LINE_OPER', N'TOPOVN_TCCL', N'LINE_OPER', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.YARD_AREA', N'TOPOVN_TCCL', N'YARD_AREA', 1, null, null),
        (N'config_stopcode', N'TOPOVN_TCCL', N'CONFIG_STOPCODE', 1, null, null),
        (N'TOPOVN_TCCL_G1.TOPOVN.CUSTOMER', N'TOPOVN_TCCL', N'CUSTOMER', 1, null, null),
        (N'ecm_class', N'ECM', N'CLASS', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'ecm_container', N'ECM', N'CONTAINER', 1, N'TOPOVN_TCCL.ITEM,TOPOVN_TCCL.PREGATE_TRANSACT,TOPOVN_TCCL.ITEM_COMMENTS,TOPOVN_TCCL.ITEM_SEAL,TOPOVN_TCCL.ITEM_SPECIAL_HANDLING,TOPOVN_TCCL.ITEM_STOPS,TOPOVN.TCCL.ITEM_LOCATION', N'ITEM_KEY'),
        (N'ecm_container_type', N'ECM', N'CONTAINER_TYPE', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'ecm_job', N'ECM', N'JOB', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'ecm_job_mode', N'ECM', N'JOB_MODE', 1, N'TOPOVN_TCCL.OPERATION_METHOD', N'OPERATION_METHOD'),
        (N'ecm_method', N'ECM', N'METHOD', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'ecm_operation', N'ECM', N'OPERATION', 1, N'TOPOVN_TCCL.LINE_OPER', N'LINE_OPER'),
        (N'ecm_reefer_container', N'ECM', N'REEFER_CONTAINER', 1, N'TOPOVN_TCCL.ITEM_REEFER,TOPOVN_TCCL.ITEM,TOPOVN_TCCL.ITEM_PTI,TOPOVN_TCCL.PREGATE_TRANSACT', N'ITEM_KEY'),
        (N'ecm_vessel_schedule', N'ECM', N'VESSEL_SCHEDULE', 1, N'TOPOVN_TCCL.VESSEL_DETAILS', N'VES_ID'),
        (N'TOPOVN_TCCL_G1.TOPOVN.VES_SERVICE', N'TOPOVN_TCCL', N'VES_SERVICE', 1, null, null),
        (N'ecm_vessel_lane', N'ECM', N'VESSEL_LANE', 1, N'TOPOVN_TCCL.VES_SERVICE', N'VES_SERVICE'),
        (N'kafka-topic-prefix.TOPOVN.GATE_NO_INFO', N'TOPOVN_TCCL', N'GATE_NO_INFO', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.GATE_LANE_INFO', N'TOPOVN_TCCL', N'GATE_LANE_INFO', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.PORTCODE', N'TOPOVN_TCCL', N'PORTCODE', 1, null, null),
        (N'ecm_port', N'ECM', N'PORT', 1, N'TOPOVN_TCCL.PORTCODE', N'PORT'),
        (N'ecm_gate', N'ECM', N'GATE', 1, N'TOPOVN_TCCL.GATE_LANE_INFO,TOPOVN_TCCL.GATE_NO_INFO', N'GATE_NO'),
        (N'ecm_container_condition', N'ECM', N'CONTAINER_CONDITION', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'ecm_customer', N'ECM', N'CUSTOMER', 1, N'TOPOVN_TCCL.CUSTOMER', N'CUST_REG_NO'),
        (N'TOPOVN_TCCL_G1.TOPOVN.VESSELS', N'TOPOVN_TCCL', N'VESSELS', 1, null, null),
        (N'ecm_vessel', N'ECM', N'VESSEL', 1, N'TOPOVN_TCCL.VESSELS', N'VES_CD'),
        (N'kafka-topic-prefix.TOPOVN.DAMAGE_CODE', N'TOPOVN_TCCL', N'DAMAGE_CODE', 1, null, null),
        (N'ecm_damage_code', N'ECM', N'DAMAGE_CODE', 1, N'TOPOVN_TCCL.DAMAGE_CODE', N'DAMAGE_CD'),
        (N'ecm_vendor', N'ECM', N'VENDOR', 1, N'TOPOVN_TCCL.SYS_CODES', N'CODE_REF'),
        (N'kafka-topic-prefix.TOPOVN.SEAL_MANAGEMENT_MASTER', N'TOPOVN_TCCL', N'SEAL_MANAGEMENT_MASTER', 1, null, null),
        (N'ecm_seal_management', N'ECM', N'SEAL_MANAGEMENT', 1, N'TOPOVN_TCCL.SEAL_MANAGEMENT_MASTER', N'SEALFORMAT'),
        (N'kafka-topic-prefix.TOPOVN.SPECIAL_HDL_CODE', N'TOPOVN_TCCL', N'SPECIAL_HDL_CODE', 1, null, null),
        (N'ecm_special_handling', N'ECM', N'SPECIAL_HANDLING', 1, N'TOPOVN_TCCL.SPECIAL_HDL_CODE', N'SPECIAL_HDL_CODE'),
        (N'kafka-topic-prefix.TOPOVN.CONTAINER_STRUCTURE', N'TOPOVN_TCCL', N'CONTAINER_STRUCTURE', 1, null, null),
        (N'ecm_container_spec', N'ECM', N'CONTAINER_SPEC', 1, N'TOPOVN_TCCL.CONTAINER_STRUCTURE', N'ITEM_NO'),
        (N'ecm_yard', N'ECM', N'YARD', 1, N'TOPOVN_TCCL.YARD_AREA,TOPOVN_TCCL.SYS_CODES', N'STACK'),
        (N'kafka-topic-prefix.TOPOVN.CHE_MASTER', N'TOPOVN_TCCL', N'CHE_MASTER', 1, null, null),
        (N'ecm_equipment', N'ECM', N'EQUIPMENT', 1, N'TOPOVN_TCCL.CHE_MASTER', N'CHE_ID'),
        (N'kafka-topic-prefix.TOPOVN.RA_COMMON', N'TOPOVN_TCCL', N'RA_COMMON', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.RA_MTY', N'TOPOVN_TCCL', N'RA_MTY', 1, null, null),
        (N'TOPOVN_TCCL_G2.TOPOVN.RA_SPECIFIC_CTRS', N'TOPOVN_TCCL', N'RA_SPECIFIC_CTRS', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.TRUCK', N'TOPOVN_TCCL', N'TRUCK', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.TRK_TRANSACT', N'TOPOVN_TCCL', N'TRK_TRANSACT', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.CTNR_MOVE_REG_MASTER', N'TOPOVN_TCCL', N'CTNR_MOVE_REG_MASTER', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.CTNR_MOVE_REG_DETAILS', N'TOPOVN_TCCL', N'CTNR_MOVE_REG_DETAILS', 1, null, null),
        (N'kafka-topic-prefix.TOPOVN.CONVERT_ISO', N'TOPOVN_TCCL', N'CONVERT_ISO', 1, null, null),
        (N'ecm_booking', N'ECM', N'BOOKING', 1, N'TOPOVN_TCCL.RA_COMMON,TOPOVN_TCCL.RA_MTY,TOPOVN_TCCL.RA_SPECIFIC_CTRS', N'RAC_KEY'),
        (N'ecm_gate_job', N'ECM', N'GATE_JOB', 1, N'TOPOVN_TCCL.TRK_TRANSACT,TOPOVN_TCCL.PREGATE_TRANSACT', N'EIR_ID'),
        (N'ecm_yard_job', N'ECM', N'YARD_JOB', 1, N'TOPOVN_TCCL.ITEM,TOPOVN_TCCL.ITEM_LOCATION,TOPOVN_TCCL.CTNR_MOVE_REG_DETAILS', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G1.TOPOVN.CONVERT_TO_ISO', N'TOPOVN_TCCL', N'CONVERT_TO_ISO', 1, null, null),
        (N'ecm_size_type', N'ECM', N'SIZE_TYPE', 1, N'TOPOVN_TCCL.CONVERT_ISO,TOPOVN_TCCL.CONVERT_TO_ISO', N'ISO'),
        (N'ecm_service_order', N'ECM', N'SERVICE_ORDER', 1, N'TOPOVN_TCCL.CTNR_MOVE_REG_MASTER,TOPOVN_TCCL.CTNR_MOVE_REG_DETAILS', N'REG_ID'),
        (N'ecm_quay_job', N'ECM', N'QUAY_JOB', 1, N'TOPOVN_TCCL.ITEM_LOCATION,TOPOVN_TCCL.ITEM,TOPOVN_TCCL.PREGATE_TRANSACT', N'ITEM_KEY'),
        (N'TOPOVN_TCCL_G2.TOPOVN.PREGATE_REEFER', N'TOPOVN_TCCL', N'PREGATE_REEFER', 1, null, null),
        (N'EPORT_NEW.EPORT.dbo.CHARGE', N'EPORT', N'CHARGE', 1, null, null),
        (N'EPORT_NEW.EPORT.dbo.INVOICE', N'EPORT', N'INVOICE', 1, null, null),
        (N'EPORT_NEW.EPORT.dbo.ORDER', N'EPORT', N'ORDER', 1, null, null),
        (N'EPORT_NEW.EPORT.dbo.ORDER_DETAIL', N'EPORT', N'ORDER_DETAIL', 1, null, null),
        (N'TOPOVN_TCCL_G8.TOPOVN.FREE_RULES', N'TOPOVN_TCCL', N'FREE_RULES', 1, null, null),
        (N'TOPOVN_TCCL_G3.TOPOVN.INVOICE', N'TOPOVN_TCCL', N'INVOICE', 1, null, null),
        (N'TOPOVN_TCCL_G3.TOPOVN.ITEM_CHARGES', N'TOPOVN_TCCL', N'ITEM_CHARGES', 1, null, null),
        (N'TOPOVN_TCCL_G2.TOPOVN.ITEM_STRIP_STUFF', N'TOPOVN_TCCL', N'ITEM_STRIP_STUFF', 1, null, null);